model = "gpt-5.4"
model_reasoning_effort = "xhigh"
web_search = "live"

[projects."/Users/th.kim/Desktop/lets-intern-client"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/buildtalk"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-web"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-analytics"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-ai-assist"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/springfall"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/node-editor"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/plausible-analytics"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/medusa"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/signals"]
trust_level = "trusted"

[projects."/Users/th.kim/run-commands"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/ClickHouse"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-medusa"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/buildtalk-infra"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/expo-test"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-web-2"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/oo"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/lets-career-server"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/zip-up"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/lead-management"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/playground-react-compiler"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/mini-hmr"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/mini-multi-scripts"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-deploy"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/playground-temporal"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/english-punch-app"]
trust_level = "trusted"

[projects."/Users/th.kim"]
trust_level = "untrusted"

[projects."/Users/th.kim/Downloads"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/codenbutter-external-api"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/purpleio-deploy-test"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/test-sigterm"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/terraform-provider-clickhouse"]
trust_level = "trusted"

[projects."/Users/th.kim/Desktop/simple-workflow"]
trust_level = "trusted"

[projects."/Users/th.kim/settings"]
trust_level = "trusted"

[projects."/Users/th.kim/codenbutter-knowledge-base"]
trust_level = "trusted"

[projects."/Users/echoja/works/springfall-astro"]
trust_level = "trusted"

[projects."/Users/echoja/works/english-punch-app"]
trust_level = "trusted"

[projects."/Users/echoja/works/buildtalk"]
trust_level = "trusted"

[projects."/Users/echoja/settings"]
trust_level = "trusted"

[projects."/Users/echoja/works"]
trust_level = "trusted"

[mcp_servers.chrome-devtools]
command = "npx"
args = [ "chrome-devtools-mcp@latest", "--autoConnect" ]
startup_timeout_sec = 60

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[sandbox_workspace_write]
network_access = true

[plugins."canva@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true
